// This is a C# function generated by ChatGPT. If you somehow stumble across it and
// wonder why its here, I placed it here simply because I couldn't be bothered to
// find a .txt program for mac.
//
// public static double[] GetRandomPointOnSphere(double x, double y, double z, double radius)
//         {
//             Random random = new Random();
//             double u = random.NextDouble();
//             double v = random.NextDouble();
//             double theta = 2 * Math.PI * u;
//             double phi = Math.Acos(2 * v - 1);
//             double xPoint = x + (radius * Math.Sin(phi) * Math.Cos(theta));
//             double yPoint = y + (radius * Math.Sin(phi) * Math.Sin(theta));
//             double zPoint = z + (radius * Math.Cos(phi));
//             return new double[] { xPoint, yPoint, zPoint };
//         }
